version: "3.7"

services:
  ##############################
  # Backend Container
  ##############################
  api:
    container_name: api
    restart: always
    image: "pallavi/sampleproject:production_14062021_api"

  ##############################
  # UI Container
  ##############################
  ui:
    image: "pallavi/sampleproject:production_14062021_ui"
    restart: always
    container_name: ui
    depends_on:
      - api
    # volumes:
    #   - ./UI/nginx/certbot/conf:/etc/letsencrypt
    #   - ./UI/nginx/certbot/www:/var/www/certbot

  # ##############################
  # # Certbot Container
  # ##############################
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./UI/nginx/certbot/conf:/etc/letsencrypt
  #     - ./UI/nginx/certbot/www:/var/www/certbot



volumes:
  humaine: